// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb6jowIR6oqe_mKxej2pnL6f6MWSKcLAo',
    appId: '1:600865897095:web:c3033bee849eead456d622',
    messagingSenderId: '600865897095',
    projectId: 'houserental-3d559',
    authDomain: 'houserental-3d559.firebaseapp.com',
    storageBucket: 'houserental-3d559.appspot.com',
    measurementId: 'G-DLCBEZ16NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsrTHZK7MSdRcFuWsYa3MvkrGXKjREQ5s',
    appId: '1:600865897095:android:e64c02aa0cc98fe956d622',
    messagingSenderId: '600865897095',
    projectId: 'houserental-3d559',
    storageBucket: 'houserental-3d559.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKNr9rFDxYo218S3YRk36B7NRYX_wtXbM',
    appId: '1:600865897095:ios:b9ff7448608f720056d622',
    messagingSenderId: '600865897095',
    projectId: 'houserental-3d559',
    storageBucket: 'houserental-3d559.appspot.com',
    iosBundleId: 'com.mlabs.houserental.houserental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKNr9rFDxYo218S3YRk36B7NRYX_wtXbM',
    appId: '1:600865897095:ios:b9ff7448608f720056d622',
    messagingSenderId: '600865897095',
    projectId: 'houserental-3d559',
    storageBucket: 'houserental-3d559.appspot.com',
    iosBundleId: 'com.mlabs.houserental.houserental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb6jowIR6oqe_mKxej2pnL6f6MWSKcLAo',
    appId: '1:600865897095:web:cd4350cd78dabcc756d622',
    messagingSenderId: '600865897095',
    projectId: 'houserental-3d559',
    authDomain: 'houserental-3d559.firebaseapp.com',
    storageBucket: 'houserental-3d559.appspot.com',
    measurementId: 'G-M752J3RZDW',
  );
}
